### ISSUE TITLE
Data origin // 数据来源

### ISSUE THREAD

**Issue by Pllamas** [sdgedfegw/Gaokao-score-distribution#1]
Hi, I am using this for research aim, and I was wondering where did this data came from (official website or elsewhere) , to know if it is credible or not to use in my research. 
Also, I am having trouble with the translation and I ask this just to check, but this data represent the cumulative distribution of the amount of students in each score, right?
I appreciate very much if someone can clarify these two aspects for me. Thanks !!

嗨，我将其用于研究目的，我想知道这些数据来自何处（官方网站或其他地方），以了解在我的研究中使用它是否可信。
另外，我翻译有问题，我问这个只是为了检查，但这个数据代表了每个分数中学生数量的累积分布，对吧？
如果有人能为我澄清这两个方面，我将不胜感激。谢谢 ！！

**Comment by sdgedfegw** [comment]
Hi, 

This data is a collection of many score distributions found on different official websites. Here's the short list of official websites that's the source of the data from at least 2010:

Beijing (北京):
https://www.bjeea.cn/
Tianjin (天津):
http://www.zhaokao.net/
Hebei (河北):
http://www.hebeea.edu.cn/
Shanxi (山西):
http://www.sxkszx.cn/index.html
Inner Mongolia (内蒙古):
https://www.nm.zsks.cn/
Liaoning (辽宁):
http://www.lnzsks.com/
Jilin (吉林):
http://www.jleea.edu.cn/
Heilongjiang (黑龙江):
https://www.lzk.hl.cn/
Shanghai (上海):
http://www.shmeea.edu.cn/
Jiangsu (江苏):
https://www.jseea.cn/index.html
Zhejiang (浙江):
https://www.zjzs.net/moban/index/index.html
Anhui (安徽):
https://www.ahzsks.cn/index.htm
Fujian (福建):
http://www.eeafj.cn/
Jiangxi (江西):
http://www.jxeea.cn/
Shandong (山东):
http://www.sdzk.cn/
Henan (河南):
http://www.heao.gov.cn/
Hubei (湖北):
http://zsxx.e21.cn/e21html/
Hunan (湖南):
http://jyt.hunan.gov.cn/jyt/sjyt/hnsjyksy/
Guangdong (广东):
http://eea.gd.gov.cn/
Guangxi (广西):
http://www.gxeea.cn/
Hainan (海南):
http://ea.hainan.gov.cn/
Chongqing (重庆):
http://www.cqksy.cn/site/index.html
Sichuan (四川):
https://www.sceea.cn/
Guizhou (贵州):
http://www.eaagz.org.cn/
Yunnan (云南):
http://www.ynzs.cn/
Tibet (西藏):
http://zsks.edu.xizang.gov.cn/
Shaanxi (陕西):
https://www.sneac.com/
Gansu (甘肃):
https://www.ganseea.cn/
Qinghai (青海):
http://www.qhjyks.com/
Ningxia (宁夏):
https://www.nxjyks.cn/
Xinjiang (新疆):
http://www.xjzk.gov.cn/

For most score distributions from older years (2009 backward), they're obtained from former, deleted official sites using Wayback Machine (https://web.archive.org/).

In several cases, the data cannot be obtained using the official website and it is obtained instead from released yearly statistics (in paper/pdf form) from the Department of Education/Examination Authority of corresponding provinces.

This data represents the cumulative distribution of the number of students in each score with the maximum score of 750 in most provinces, 900 in Hainan province, 600 in Shanghai between 2014-2016 and 660 from 2017 onward, 480 in Jiangsu province between 2008-2020 and 810 in Zhejiang province between 2008-2016 in a set of Natural Science (理科) or Liberal Arts (文科) subjects. 

There are 2 .xlsx files in each folder, each contains the listed year (in the range of 2000-2021) and subject set (Natural Science (理科) or Liberal Arts (文科) (in the file's name)'s score distribution.

Each listed year each .xlsx table occupy 3 columns and is represents by the score range (the first column) in descending order., number of students in that score range (second column) and cumulative total (third column). 

It should be noted that different provinces have different exam and exam system. Here's the introduction of specific exam systems across China (from Wikipedia).

"3+X" system: 
As a pilot examination system used in order to promote education system reform, this examination system has been implemented in most parts of the country, including Beijing City, Tianjin City, Hebei Province, Liaoning Province, Jilin Province, Heilongjiang Province, Anhui Province, Fujian Province, Guangdong Province, Jiangxi Province, Henan Province, Shandong Province, Hubei Province, Shaanxi Province, Sichuan Province, Guizhou Province, Yunnan Province, Shanxi Province, Chongqing City, Gansu Province, Qinghai Province, Inner Mongolia, Guangxi, Ningxia, Xinjiang and Tibet. In the context of the reform of the National College Entrance Examination, this program will be suspended in Beijing, Tianjin, Shandong and Hainan provinces from 2020, and will be suspended in most provinces and cities in China from 2021. It will cease across Mainland China by 2022.

"3" refers to compulsory subjects, including "Chinese, Mathematics and a foreign language", each of which accounts for 150/750 in total score.
"X" means that students can choose, according to their own capability, one subject from either Social Sciences (including Political Sciences, History and Geography), or Natural Sciences (including Physics, Chemistry and Biology), which accounts for 300/750 in total score.
If a student chooses Natural Sciences, then he or she will take a relatively harder mathematics test as well, including Curves and Equations, Space Vector and Solid Geometry, The Concept of Definite Integral, Fundamental Theorem of Calculus, Simple Application of Definite Integral, Mathematical Induction, Counting Principle, Random Variable and Its Distribution.
For candidates of minor ethnic groups in Tibet, Xinjiang, Inner Mongolia, Qinghai and Jilin, their Literature score consists of an easier Chinese Literature test and an optional subject on Tibetan, Mongolian, Uyghur and Korean Literature, each counting for 75 points.

"3+X+Y" system
The system was used in Zhejiang Province, with the last exam offered in 2016 to "Class-of-2013" (Chinese: 2013级, meaning admitted to senior high school in 2013, i.e., being Grade 10 in 2013) while "Class-of-2014" students have been taking the reformed version of Gaokao since 2017.

The "3" and "X" are the same as the national "3+X" system, weighed 750 points. The "Y" part consists of 18 problems, covering 9 subjects (Chinese, Maths, English, Physics, Chemistry, Biology, History, Politics, and Geography), from which students need to choose 6 problems to answer, weighed 60 points. The total score is 810 points.

"3+2" system
This system used to be employed in Jiangsu Province, but is being replaced by another system in 2020. The total score was 480 points.

"3" refers to three compulsory subjects "Chinese, mathematics and a foreign language", which are recorded in the total score.
"2" refers to selecting two subjects either from Politics, History or Geography for arts students, or from Biology, Chemistry or Physics for science students, which are not recorded in total score but a class like A, B, etc. will be recorded.
Bonus Points: refers to 4 comprehensive science or liberal arts exams, one gets a bonus of 5 points if they get 4 "A"s in all 4 elective exams.
"4+X" system
This system was used after the New Curriculum Reform being employed in Guangdong province, and now it has been abandoned.

"X" means that according to their own interests, candidates can choose one or two subjects either from arts subjects, including Politics, History and Geography (Politics and Geography cannot be chosen simultaneously), or from science subjects, including Biology, Physics and Chemistry (Physics and Biology cannot be chosen simultaneously).
Chinese and a foreign language are compulsory. Two separate Mathematics tests are designed respectively for arts students and science students.
In addition to three compulsory subjects and X subject, arts students have to take comprehensive tests of arts, and science students have to take comprehensive tests of science.
"3+1+X" system
This system has been implemented in Shanghai since the employment of comprehensive courses, now abandoned.

"3" refers to three compulsory subjects "Chinese, Mathematics and a foreign language", with 150 scores for each subject.
"1" refers to one subject that candidates choose according to their own interests and specialty from "Politics, History, Geography, Physics, Chemistry and Biology". This subject accounts 150 scores when admitted by universities and colleges at undergraduate level. The score is not included in the total score when admitted by vocational and technical colleges. Therefore, candidates can give up this subject when applying for colleges at vocational and technical level.
"X" refers to comprehensive ability test, which is categorized into arts tests and science tests. Arts students can either choose one subject from Politics, History and Geography, or take an arts comprehensive test when giving up "1' subject. Science students can either choose one subject from Physics, Chemistry and Biology, or take a science comprehensive test when giving up "1" subject. Regardless of arts and science categories, all the comprehensive ability tests cover knowledge of six subjects,including Politics, History, Geography, Physics, Chemistry and Biology. In the first volume of the arts test, number of questions related to arts subjects exceeds science questions, and vice versa; the second volume of the two tests are the same.
"3+2+X" system
This is a pilot college entrance examination system implemented by the Jiangsu Province in 2003 after examining other testing systems, but it was replaced by "3+2" system in 2008. Subject tests will take turns into the embrace of National Standard. A new policy substituted the old one in 2021.

"3" refers to three compulsory subjects "Chinese, mathematics and a foreign language", which are recorded in the total score.
"2" refers to choosing two subjects from the following six areas "politics, history, geography, physics, chemistry, biology", which are not recorded in total score but a class like A+, A, etc. will be recorded.
"X" refers to a comprehensive science or liberal arts exam, which is not recorded in the total score, only for university admission reference.
"3+X+1" system
This is part of the curriculum reform in China.

"3" refers to Chinese, Mathematics and a foreign language, which are compulsory testing subjects for each candidate.
"X" means choosing one of the two comprehensive tests in either sciences or liberal arts, according to the student's interest. The "3" and "X" are the same as the national "3+X" system.
"1" refers to a basic proficiency test on skills (基本能力测试) that high school graduates needs and should have in order to adapt to social life. This college entrance examination system was implemented for the first time in Shandong in 2007 and ended in 2014.
The examination system in Shandong Province reverted to the "3+X" system as of the most recent testing in June 2014 and took the reform plan from 2020.

This table lists exam systems and exam papers in each provinces in different years:

![image](https://user-images.githubusercontent.com/64156388/226011483-fdab0f91-d673-4bb2-8dbd-c873e54f29d5.png)

Thanks for asking.
